import ROOT
items = [
  {"name":"lowmtw",
   "mode":"range",
   "before":2,
   "after":3,
   "y1":0.1,
   "y2":1000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"lowmtw",
   "mode":"range",
   "before":1,
   "after":2,
   "y1":0.1,
   "y2":600,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"high mll",
   "mode":"text",
   "x":2.05,
   "y":40,
   "size":0.035,
   "text":"M_{Z2} #geq 60 GeV",
   "doOnRatio":True,
   "angle":90
  },
  {"name":"high mll",
   "mode":"text",
   "x":3.05,
   "y":40,
   "size":0.035,
   "text":"M_{Z2} < 60 GeV",
   "doOnRatio":True,
   "angle":90
  },
]
