import ROOT
items = [
  {"name":"lowmet",
   "mode":"range",
   "before":1,
   "after":3,
   "y1":0.5,
   "y2":8000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"midmet",
   "mode":"range",
   "before":4,
   "after":6,
   "y1":0.5,
   "y2":8000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"highmet",
   "mode":"range",
   "before":7,
   "after":9,
   "y1":0.5,
   "y2":10000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },

  {"name":"lowmet",
   "mode":"text",
   "x":1.55,
   "y":2000,
   "size":0.039,
   "text":"50 GeV < p_{T}^{miss} < 200 GeV",
   "doOnRatio":True,
  },

  {"name":"lowmet",
   "mode":"text",
   "x":4.05,
   "y":2000,
   "size":0.039,
   "text":"200 GeV < p_{T}^{miss} < 300 GeV",
   "doOnRatio":True,
  },

  {"name":"lowmet",
   "mode":"text",
   "x":7.4,
   "y":2000,
   "size":0.039,
   "text":"p_{T}^{miss} > 300 GeV",
   "doOnRatio":True,
  },

  {"name":"lowmet",
   "mode":"text",
   "x":1.45,
   "y":-1.15,
   "size":0.15,
   "text":"M_{T2} (GeV)",
   "doOnRatio":True,
   "forceRatio":True,
  },
  {"name":"lowmet",
   "mode":"text",
   "x":4.45,
   "y":-1.15,
   "size":0.15,
   "text":"M_{T2} (GeV)",
   "doOnRatio":True,
   "forceRatio":True,
  },
  {"name":"lowmet",
   "mode":"text",
   "x":7.35,
   "y":-1.15,
   "size":0.15,
   "text":"M_{T}(ll) (GeV)",
   "doOnRatio":True,
   "forceRatio":True,
  },
]
