import ROOT
items = [
  {"name":"dr",
   "mode":"range",
   "before":3,
   "after":3,
   "y1":0.1,
   "y2":150,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"high dr",
   "mode":"text",
   "x":2.6,
   "y":80,
   "size":0.05,
   "text":"#Delta R^{H} < 0.8",
   "doOnRatio":True,
  },
  {"name":"high mll",
   "mode":"text",
   "x":1.15,
   "y":80,
   "size":0.05,
   "text":"#Delta R^{H} #geq 0.8",
   "doOnRatio":True,
  },
]
