import ROOT
items = [
  {"name":"lowmt2",
   "mode":"range",
   "before":1,
   "after":5,
   "y1":0.5,
   "y2":3500,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"highmt2",
   "mode":"range",
   "before":6,
   "after":9,
   "y1":0.5,
   "y2":2000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"lowmll",
   "mode":"range",
   "before":1,
   "after":3,
   "y1":0.5,
   "y2":1000,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"midmll",
   "mode":"range",
   "before":6,
   "after":7,
   "y1":0.5,
   "y2":1000,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":3.7,
   "y":1600,
   "size":0.05,
   "text":"M_{T2}(l,#tau_{h}) < 80 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":5.6,
   "y":1600,
   "size":0.05,
   "text":"M_{T2}(l,#tau_{h}) #geq 80 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":1.5,
   "y":600,
   "size":0.04,
   "text":"M_{l#tau_{h}} #leq 50 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":4.,
   "y":600,
   "size":0.04,
   "text":"M_{l#tau_{h}} > 50 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":6.,
   "y":600,
   "size":0.04,
   "text":"M_{l#tau_{h}} #leq 100 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":8.,
   "y":600,
   "size":0.04,
   "text":"M_{l#tau_{h}} > 100 GeV",
   "doOnRatio":True,
  },

]
