import ROOT
items = [
  {"name":"lowmtw",
   "mode":"range",
   "before":1,
   "after":14,
   "y1":0.5,
   "y2":10000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"highmt2",
   "mode":"range",
   "before":15,
   "after":16,
   "y1":0.5,
   "y2":10000,
   "style":1,
   "color":ROOT.kBlue+3,
   "widht":4,
   "doOnRatio":True,
  },
  {"name":"lowmll",
   "mode":"range",
   "before":1,
   "after":5,
   "y1":0.5,
   "y2":2000,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"midmll",
   "mode":"range",
   "before":6,
   "after":10,
   "y1":0.5,
   "y2":2000,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"highmll",
   "mode":"range",
   "before":11,
   "after":14,
   "y1":0.5,
   "y2":2000,
   "style":9,
   "color":ROOT.kBlue+3,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"highmt2",
   "mode":"text",
   "x":14.6,
   "y":3000,
   "size":0.050,
   "text":"#splitline{M_{T2}(ll)}{#geq 80 GeV}",
   "doOnRatio":True,
  },
  {"name":"lowmt2",
   "mode":"text",
   "x":11.5,
   "y":5000,
   "size":0.050,
   "text":"M_{T2}(ll) < 80 GeV",
   "doOnRatio":True,
  },
  {"name":"low mll",
   "mode":"text",
   "x":2.5,
   "y":1000,
   "size":0.035,
   "text":"M_{ll} < 60 GeV",
   "doOnRatio":True,
  },
  {"name":"mid mll",
   "mode":"text",
   "x":6.8,
   "y":1000,
   "size":0.035,
   "text":"60 GeV #leq M_{ll} < 100 GeV",
   "doOnRatio":True,
  },
  {"name":"high mll",
   "mode":"text",
   "x":11.7,
   "y":1000,
   "size":0.035,
   "text":"M_{ll} #geq 100 GeV",
   "doOnRatio":True,
  },
]
