import os
from getCardsModule import*

dr1 = " LepGood_pt[0]:LepGood_pt[0] 4,0.,300.,4,0.,300. "
funcdr1  = " 4:PT12Dto1D_4 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_4BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_4BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 6,0.,300.,6,0.,300. "
funcdr1  = " 6:PT12Dto1D_6 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_6BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_6BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 8,0.,300.,8,0.,300. "
funcdr1  = " 8:PT12Dto1D_8 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_8BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_8BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 10,0.,300.,10,0.,300. "
funcdr1  = " 10:PT12Dto1D_10 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_10BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_10BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 12,0.,300.,12,0.,300. "
funcdr1  = " 12:PT12Dto1D_12 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_12BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_12BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 14,0.,300.,14,0.,300. "
funcdr1  = " 14:PT12Dto1D_14 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_14BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_14BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 16,0.,300.,16,0.,300. "
funcdr1  = " 16:PT12Dto1D_16 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_16BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_16BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 18,0.,300.,18,0.,300. "
funcdr1  = " 18:PT12Dto1D_18 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_18BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_18BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)

dr1 = " LepGood_pt[0]:LepGood_pt[0] 20,0.,300.,20,0.,300. "
funcdr1  = " 20:PT12Dto1D_20 "
outdr1_c = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_CAT_20BINS "
outdr1_nc = " /afs/cern.ch/user/c/cericeci/private/CMSSW_7_4_7/HiggsAnalysis/CombinedLimit/scripts/cards/PT1_NOCAT_20BINS "
getCatCards(base,funcdr1,dr1,outdr1_c)
getUnCatCards(base,funcdr1,dr1,outdr1_nc)
